#!/usr/bin/env node
/**
 * Turns content/catalogue-labels.json into SQL that fills the `labels`
 * columns of public.categories and public.articles.
 *
 *   node scripts/db/labels-to-sql.mjs [--out supabase/seed/catalogue-labels.sql]
 *
 * content/catalogue-labels.json:
 *   {
 *     "categories": { "<category key>": { "nl": "…", "fr": "…" } },
 *     "descriptions": { "<English article description>": { "nl": "…", "fr": "…" } }
 *   }
 *
 * Article labels are keyed by the English description, not the article
 * code: "White RAL 9016" is one string on fourteen articles, and a new
 * price list keeps the descriptions while it may renumber nothing or
 * everything. The importer (price-list-to-sql.mjs) reads the same file to
 * put the labels into the committed snapshot.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const args = process.argv.slice(2);
const outIdx = args.indexOf('--out');
const OUT = outIdx >= 0 ? args[outIdx + 1] : 'supabase/seed/catalogue-labels.sql';

const labels = JSON.parse(readFileSync('content/catalogue-labels.json', 'utf8'));
const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;

const lines = [];
lines.push('-- Generated by scripts/db/labels-to-sql.mjs from content/catalogue-labels.json.');
lines.push('-- Fills the translation columns; safe to re-run.');
for (const [key, byLocale] of Object.entries(labels.categories ?? {})) {
  lines.push(`update public.categories set labels = ${j(byLocale)} where key = ${q(key)};`);
}
for (const [description, byLocale] of Object.entries(labels.descriptions ?? {})) {
  lines.push(`update public.articles set labels = ${j(byLocale)}, updated_at = now() where description = ${q(description)};`);
}
lines.push(`select (select count(*) from public.categories where labels <> '{}'::jsonb) as categories_labelled,
       (select count(*) from public.articles where labels <> '{}'::jsonb) as articles_labelled,
       (select count(*) from public.articles where labels = '{}'::jsonb and active) as articles_without_labels;`);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`${OUT}: ${Object.keys(labels.categories ?? {}).length} categories, ${Object.keys(labels.descriptions ?? {}).length} descriptions`);
