import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import matter from 'gray-matter';

/**
 * Editorial blog posts imported from the content workbook
 * (content/blog/<locale>/<slug>.md, generated by scripts/content/import-workbook.mjs).
 *
 * These posts are single-locale: no hreflang alternates, listed only in
 * their own locale's index and sitemap. Drafts (draft: true) are rendered
 * for preview but noindex and excluded from index and sitemap.
 */

export interface PostFaq {
  question: string;
  answer: string;
}

export interface PostAuthor {
  name: string;
  jobTitle?: string;
  url?: string;
}

export interface ContentPost {
  id: string;
  slug: string;
  locale: string;
  title: string;
  description: string;
  h1: string;
  keyword: string;
  secondaryKeywords: string[];
  intent: string;
  category: string;
  author: PostAuthor;
  datePublished: string;
  dateModified: string;
  heroImage: string;
  heroImageMissing: string | null;
  heroAlt: string;
  internalLinks: string[];
  cta: string;
  sources: string;
  faq: PostFaq[];
  draft: boolean;
  status?: string;
  wordCount: number;
  /** Markdown body without the H1 */
  body: string;
}

const CONTENT_DIR = join(process.cwd(), 'content', 'blog');

function parse(locale: string, file: string): ContentPost | null {
  const raw = readFileSync(join(CONTENT_DIR, locale, file), 'utf8');
  const { data, content } = matter(raw);
  if (!data.slug || !data.title) return null;
  return {
    id: String(data.id ?? ''),
    slug: String(data.slug),
    locale,
    title: String(data.title),
    description: String(data.description ?? ''),
    h1: String(data.h1 ?? data.title),
    keyword: String(data.keyword ?? ''),
    secondaryKeywords: Array.isArray(data.secondaryKeywords) ? data.secondaryKeywords.map(String) : [],
    intent: String(data.intent ?? ''),
    category: String(data.category ?? 'education'),
    author: typeof data.author === 'object' && data.author ? (data.author as PostAuthor) : { name: String(data.author ?? 'Re-Sound') },
    datePublished: String(data.datePublished ?? ''),
    dateModified: String(data.dateModified ?? data.datePublished ?? ''),
    heroImage: String(data.heroImage ?? ''),
    heroImageMissing: data.heroImageMissing ? String(data.heroImageMissing) : null,
    heroAlt: String(data.heroAlt ?? ''),
    internalLinks: Array.isArray(data.internalLinks) ? data.internalLinks.map(String) : [],
    cta: String(data.cta ?? ''),
    sources: String(data.sources ?? ''),
    faq: Array.isArray(data.faq) ? (data.faq as PostFaq[]).filter((f) => f && f.question && f.answer) : [],
    draft: Boolean(data.draft),
    status: data.status ? String(data.status) : undefined,
    wordCount: Number(data.wordCount ?? 0) || content.split(/\s+/).filter(Boolean).length,
    body: content.trim(),
  };
}

/** All posts of a locale, newest first. Drafts only when asked for. */
export function getContentPosts(locale: string, opts: { includeDrafts?: boolean } = {}): ContentPost[] {
  const dir = join(CONTENT_DIR, locale);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => parse(locale, f))
    .filter((p): p is ContentPost => p !== null && (opts.includeDrafts || !p.draft))
    .sort((a, b) => (a.datePublished < b.datePublished ? 1 : -1));
}

export function getContentPost(locale: string, slug: string): ContentPost | null {
  const dir = join(CONTENT_DIR, locale);
  if (!existsSync(dir)) return null;
  const file = readdirSync(dir).find((f) => f === `${slug}.md`);
  return file ? parse(locale, file) : null;
}

/** Every (locale, slug) pair, drafts included, for generateStaticParams. */
export function allContentPostParams(): Array<{ locale: string; slug: string }> {
  if (!existsSync(CONTENT_DIR)) return [];
  return readdirSync(CONTENT_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .flatMap((d) => getContentPosts(d.name, { includeDrafts: true }).map((p) => ({ locale: d.name, slug: p.slug })));
}
