/**
 * Edge-safe route knowledge for the middleware's zero-404 layer.
 *
 * Imports only plain data modules (no Node APIs): which locale-stripped paths
 * are pages of this site. Anything else that reaches the middleware is a
 * legacy or mistyped URL and is redirected to the closest live index instead
 * of rendering a 404 (see src/middleware.ts).
 *
 * Keep STATIC_ROUTES in step with src/app/[locale]/<route>/page.tsx.
 */
import { BOOTH_GUIDE } from '@/data/guides';
import { HUBS } from '@/data/hubs';
import { MANUFACTURING_SLUGS } from '@/data/manufacturing';
import { PRODUCT_SLUGS } from '@/data/products';
import editorialBlogSlugs from '@/data/generated/blog-slugs.json';

/** Locale-stripped paths that are pages in every locale. */
const STATIC_ROUTES = new Set<string>([
  '/',
  '/about',
  '/blog',
  '/contact',
  '/faq',
  '/partner',
  '/privacy',
  '/products',
  '/samples',
  '/acoustic-calculator',
  '/sustainability',
  '/terms',
  '/where-to-buy',
]);

/** /products/<slug>: product pages plus every hub slug in every locale. */
const PRODUCT_PATHS = new Set<string>([
  ...PRODUCT_SLUGS.map((s) => `/products/${s}`),
  ...Object.values(HUBS).flatMap((hub) => [hub.internalPath, ...Object.values(hub.slugs).map((s) => `/products/${s}`)]),
]);

/** /guides/<slug> in any locale's spelling. */
const GUIDE_PATHS = new Set<string>(Object.values(BOOTH_GUIDE.slugs).map((s) => `/guides/${s}`));

/** /manufacturing and its localised spellings. */
const MANUFACTURING_PATHS = new Set<string>(Object.values(MANUFACTURING_SLUGS).map((s) => `/${s}`));

/**
 * Blog slugs: the four message-driven posts exist in every locale; the
 * editorial posts (content/blog/<locale>/*.md, drafts included) in their own
 * locale only. The per-locale list is generated by scripts/build-blog-slugs.mjs
 * (prebuild) because the edge cannot read content/. Keep LEGACY_BLOG_SLUGS in
 * step with src/app/[locale]/blog/[slug]/page.tsx.
 */
const LEGACY_BLOG_SLUGS = new Set<string>([
  'circular-economy-acoustics',
  'office-acoustic-solutions',
  'recycled-materials-quality',
  'sound-absorption-explained',
]);
const EDITORIAL_BLOG_SLUGS: Record<string, Set<string>> = Object.fromEntries(
  Object.entries(editorialBlogSlugs as Record<string, string[]>).map(([locale, slugs]) => [locale, new Set(slugs)]),
);
const ANY_LOCALE_BLOG_SLUGS = new Set<string>(Object.values(editorialBlogSlugs as Record<string, string[]>).flat());

/** True when /blog/<slug> is a post in the given locale (any locale when none is given). */
export function isBlogSlug(slug: string, locale?: string): boolean {
  if (LEGACY_BLOG_SLUGS.has(slug)) return true;
  if (locale) return EDITORIAL_BLOG_SLUGS[locale]?.has(slug) ?? false;
  return ANY_LOCALE_BLOG_SLUGS.has(slug);
}

/** Normalise a locale-stripped pathname: no trailing slash, no doubled slashes. */
export function normalizePath(pathname: string): string {
  const cleaned = ('/' + pathname).replace(/\/{2,}/g, '/').replace(/\/+$/, '');
  return cleaned === '' ? '/' : cleaned;
}

/**
 * True when the locale-stripped path is one of the site's own routes. Blog
 * posts are checked against the generated slug list for the locale (an
 * unprefixed /blog/<slug> is accepted when any locale has the post: next-intl
 * adds the locale on the next hop and the check runs again).
 */
export function isKnownRoute(pathname: string, locale?: string): boolean {
  const path = normalizePath(pathname);
  if (STATIC_ROUTES.has(path)) return true;
  if (PRODUCT_PATHS.has(path)) return true;
  if (GUIDE_PATHS.has(path)) return true;
  if (MANUFACTURING_PATHS.has(path)) return true;
  if (path.startsWith('/blog/')) {
    const rest = path.slice('/blog/'.length);
    return !rest.includes('/') && isBlogSlug(rest, locale);
  }
  return false;
}

/**
 * Where an unknown path should land: the closest live index for the section
 * it pretends to be in, else the locale home. Locale-stripped in, locale-
 * stripped out.
 */
export function closestRoute(pathname: string): string {
  const path = normalizePath(pathname);
  if (path.startsWith('/products/') || path.startsWith('/product-page')) return '/products';
  if (path.startsWith('/guides/')) return '/guides/phone-booth-prices';
  if (path.startsWith('/blog') || path.startsWith('/post/')) return '/blog';
  return '/';
}

/**
 * Files and folders that can be served from public/ or by a generated route
 * (favicon, robots, llms, sitemap). Files match exactly, folders by prefix:
 * an unprefixed asset-like request that is neither cannot be a real file, so
 * the middleware sends it to the home page instead of letting a bogus first
 * segment ("sitemap_index.xml", "wp-login.php") reach the [locale] tree.
 * Keep in step with public/.
 */
const PUBLIC_FILES = new Set<string>([
  '/favicon.ico',
  '/apple-touch-icon.png',
  '/icon-192.png',
  '/robots.txt',
  '/llms.txt',
  '/sitemap.xml',
  '/README.md',
]);
const PUBLIC_DIRS = ['/images/', '/documents/', '/videos/', '/.well-known/'];

/** True when an asset-like path could be served from public/ or a generated route. */
export function isPublicAssetPath(pathname: string): boolean {
  return PUBLIC_FILES.has(pathname) || PUBLIC_DIRS.some((d) => pathname.startsWith(d));
}
